/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
static yyconst short int yy_accept[338] =
    {   0,
        0,    0,    0,    0,  103,  101,   99,  100,   98,   84,
      101,  101,   90,   83,  101,   78,   79,   88,   87,   75,
       86,   82,   89,   45,   45,   76,   72,   91,   77,   92,
       95,   41,   41,   80,   81,   93,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   73,   94,   74,   85,    6,    5,    6,    6,   71,
        0,   42,    0,    0,    0,   57,   74,   66,   58,    0,
        0,   55,   63,   53,   64,   54,   65,    0,   48,    2,
        1,   56,   49,   44,   45,   45,   45,    0,   45,   45,
       81,   73,   80,   62,   68,   70,   69,   61,    0,    0,

       41,   41,   41,   41,    0,    0,    0,   59,   41,   41,
       41,   41,   41,   41,   14,   41,   41,   41,   41,   41,
       41,   22,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   60,   67,    4,    3,    0,    0,   46,
       50,    0,   48,   48,    1,   48,    0,   49,   49,   44,
       44,    0,   45,   43,    0,   52,   51,   41,    0,    0,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   20,   41,   23,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,    0,
        0,    0,   48,    0,    0,   48,   48,    0,   49,    0,

        0,   47,   45,   45,   43,   43,    0,   41,   39,    0,
        0,   40,    0,    7,   41,    9,   10,   41,   41,   41,
       41,   16,   17,   41,   41,   21,   24,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   36,   41,
       41,    0,    0,    0,    0,   48,    0,    0,    0,   47,
       47,    0,    0,    0,   41,    0,    0,    0,    8,   11,
       41,   41,   41,   41,   19,   41,   41,   27,   41,   41,
       41,   41,   41,   41,   34,   41,   41,   38,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   41,    0,
       41,   41,   15,   18,   41,   26,   28,   29,   30,   31,

       32,   41,   41,   41,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   41,   13,   41,   33,   41,   41,
        0,   97,    0,    0,    0,    0,    0,    0,   12,   25,
       35,   37,    0,   96,    0,   45,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   31,   30,   30,   32,   30,   30,
       33,   34,   35,   36,   30,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   30,   46,   47,   48,   49,
       50,   51,   30,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[345] =
    {   0,
        0,    0,   62,   63,  824,  825,  825,  825,  825,  799,
       61,   28,   45,   62,  788,  825,  825,  787,   58,  825,
       63,   72,   72,   80,   74,  783,  825,  102,  772,   53,
      825,  133,  175,   85,  825,  770,  737,  738,   87,   33,
       87,   66,  739,   91,  738,  745,   97,  726,  734,  732,
      737,  825,  104,  825,  825,  825,  825,  761,  765,  825,
      123,  825,  772,  733,  724,  825,  825,  825,  825,  134,
      145,  825,  825,  825,  825,  825,  825,  755,  179,  825,
        0,  825,  190,  192,  208,  224,  198,    0,  210,    0,
      825,  825,  825,  743,  825,  825,  825,  711,  124,  700,

      140,  190,  236,  246,   95,  214,  241,  825,  249,  256,
      195,  258,  263,  264,  265,  276,  266,  278,  106,  275,
      284,  292,  299,  305,  304,  312,  318,  320,  329,  330,
      331,  338,  345,  825,  825,  825,  825,  679,  680,  825,
      825,  349,  825,  668,    0,  351,  375,  825,  651,  261,
      355,  259,  380,  312,  629,  825,  825,  350,  314,  388,
      391,  336,  405,  408,  414,  415,  426,  428,  427,  433,
      434,  439,  441,  444,  447,  449,  452,  460,  455,  467,
      466,  472,  474,  473,  475,  486,  483,  489,  491,  615,
      611,  280,  490,  590,  486,  825,  592,  368,  510,  578,

      571,  514,    0,  504,  456,  513,  562,  511,  825,  550,
      562,  825,  278,  512,  530,  536,  543,  552,  557,  565,
      567,  568,  573,  574,  575,  576,  581,  582,  584,  583,
      589,  590,  597,  595,  602,  603,  605,  612,  611,  613,
      618,  523,  500,  496,  386,  619,  494,  493,  487,  825,
      483,  459,  444,  447,  621,  393,  644,  432,  639,  640,
      641,  557,  646,  647,  659,  662,  664,  665,  670,  672,
      678,  671,  679,  687,  688,  689,  694,  695,  422,  416,
      407,  388,  390,  387,  372,  365,  349,  330,  696,  323,
      697,  462,  702,  705,  712,  714,  720,  721,  723,  726,

      731,  734,  736,  737,  372,  325,  312,  311,  298,  293,
      271,  248,  222,  213,  739,  744,  745,  750,  751,  752,
      232,  825,  208,  145,  128,  115,   97,   95,  753,  758,
      759,  760,  100,  825,   46,  740,  825,  797,  801,  805,
      809,   80,  813,  817
    } ;

static yyconst short int yy_def[345] =
    {   0,
      337,    1,  338,  338,  337,  337,  337,  337,  337,  337,
      339,  337,  337,  337,  340,  337,  337,  337,  337,  337,
      337,  337,  337,  337,   24,  337,  337,  337,  337,  337,
      337,  337,   32,  337,  337,  337,   32,   32,   32,   32,
       32,   32,   33,   33,   33,   33,   33,   33,   33,   33,
       33,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      339,  337,  339,  337,  337,  337,  337,  337,  337,  340,
      340,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      341,  337,  337,   24,   25,   85,  337,  342,  337,   25,
      337,  337,  337,  337,  337,  337,  337,  337,  339,  340,

       32,   33,   33,   33,  337,  337,  337,  337,   33,   33,
       32,   33,   33,   32,   33,   33,   33,   33,  116,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  341,  337,  337,  337,  337,  337,
      337,  337,   85,  342,  337,  337,  337,   33,  337,  337,
       33,   33,   33,   33,   33,   32,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,

      337,  337,   85,  337,  337,  337,  337,   33,  337,  337,
      337,  337,  337,   33,   33,   33,   33,   33,   33,   32,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,   33,  337,  337,  337,   33,   33,
       33,  116,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,   33,  337,
       33,  116,   33,   33,   33,   33,   33,   33,   33,   33,

       33,   33,   33,   33,  343,  337,  337,  337,  337,  337,
      337,  337,  337,  337,   33,   33,   33,   33,   33,   33,
      343,  337,  344,  337,  337,  337,  337,  337,   33,   33,
       33,   33,  344,  337,  337,  337,    0,  337,  337,  337,
      337,  337,  337,  337
    } ;

static yyconst short int yy_nxt[890] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   32,   32,   33,
       33,   33,   34,    6,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   33,   44,   33,   45,   33,   33,   33,
       33,   46,   47,   48,   49,   50,   51,   33,   33,   33,
       52,   53,   54,   55,   57,   57,   62,   64,   66,   67,
       68,   73,   65,  114,   58,   58,   97,   98,   75,   59,
       59,   74,  115,  154,   80,   69,   76,   77,   78,   81,
       79,   79,   90,   90,   63,   82,   83,  250,   84,   84,

      105,  106,  334,  107,  107,  337,   85,   86,   85,   92,
       87,   88,  119,  159,  159,  120,   85,   85,   85,   85,
       86,   85,   93,  111,   94,   95,   89,  134,   62,   62,
      112,  337,  122,  116,   87,  117,  113,   88,   99,  123,
      126,  127,  100,  140,  118,  337,  211,  337,  205,  337,
      128,  101,  101,  129,   70,  171,   63,   63,  102,  101,
      101,  101,  102,  103,  102,  135,  336,   71,  335,  101,
      101,  101,  101,  101,  101,  102,  102,  102,  102,  104,
      102,  102,  102,  102,  102,  102,  102,  103,  102,  102,
      102,  102,  102,  102,  102,  337,  196,   79,   79,  337,

      337,  102,  102,  102,  337,  102,  142,  143,  146,  146,
      334,  102,  102,  102,  102,  102,  102,  147,  148,  142,
      143,  102,  150,  337,  337,  144,   85,   85,   87,  102,
      147,  148,  160,  160,  322,   85,  149,  152,  151,  152,
       87,  337,  153,  153,   89,  337,  150,  163,   85,  337,
      155,  337,   87,  328,  337,  337,   89,  106,  337,  107,
      107,  337,  327,  337,   87,  337,  103,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  103,  202,  202,  103,
      337,  337,  104,  337,  337,  337,  158,  337,  326,  337,
      103,  150,  104,  337,  164,  104,  162,  337,  193,  193,

      103,  337,  161,  103,  337,  166,  103,  151,  337,  337,
      337,  165,  212,  337,  337,  150,  158,  337,  258,  167,
      169,  337,  104,  337,  325,  337,  172,  337,  168,  337,
      103,  170,  159,  159,  337,  337,  337,  173,  337,  337,
      337,  337,  205,  337,  150,  337,  176,  337,  209,  148,
      337,  324,  174,  175,  337,  337,  181,  177,  206,  337,
      179,  178,  192,  143,  192,  323,  205,  193,  193,  146,
      146,  182,  215,  183,  322,  185,  314,  180,  195,  196,
      184,   87,  187,  186,  188,  150,  199,  199,  198,  189,
      198,  195,  196,  199,  199,  201,  337,  197,  153,  153,

      337,  151,  313,  208,  246,  246,  160,  160,  203,  150,
      337,  257,  257,  337,  337,  210,  211,  337,  312,  337,
      337,  203,  212,  337,  337,  311,  204,  310,  210,  211,
      309,  337,  337,  337,  213,  337,  337,  337,  337,  337,
      214,  308,  337,  337,  337,  216,  337,  307,  337,  337,
      337,  220,  337,  337,  337,  306,  337,  337,  337,  217,
      337,  337,  305,  221,  337,  337,  218,  219,  222,  337,
      225,  337,  337,  224,  223,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  290,  205,  288,  337,  227,
      226,  337,  337,  228,  337,  337,  337,  287,  337,  245,

      337,  245,  206,  231,  246,  246,  229,  232,  193,  193,
      205,  230,  286,  236,  102,  316,  337,  337,  143,  233,
      337,  337,  239,  285,  237,  240,  234,  235,  199,  199,
      238,  143,  202,  202,   87,  337,  144,  241,  148,  337,
      284,  337,  250,  205,  252,  337,  283,  282,  337,  281,
       89,  148,  337,  253,  280,  250,  149,  337,   87,  206,
      251,  337,  337,  256,  255,  256,  337,  205,  257,  257,
      337,  279,  337,  337,  337,  259,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  212,  102,  337,  337,

      337,  261,  337,  292,  337,  260,  337,  337,  337,  102,
      337,  337,  337,  263,  337,  254,  337,  337,  337,  262,
      337,  337,  337,  337,  249,  264,  337,  337,  265,  269,
      337,  248,  247,  272,  266,  267,  268,  246,  246,  270,
      273,  271,  274,  244,  337,  337,  337,  196,  337,  337,
      337,  337,  337,  275,  276,  337,  337,  243,  278,  242,
      196,  289,  257,  257,  337,  197,  277,  337,  337,  337,
      337,  337,  211,  337,  337,  337,  337,  337,  212,  337,
      337,  337,  207,  337,  337,  211,  293,  337,  337,  291,
      213,  200,  337,  337,  337,  294,  337,  337,  337,  337,

      337,  337,  337,  337,  337,  337,  337,  337,  194,  297,
      337,  337,  296,  298,  337,  295,  299,  337,  191,  337,
      190,  337,  301,  337,  300,  337,  337,  302,  337,  337,
      337,  337,  337,   71,  157,  337,  337,  303,  304,  337,
      337,  337,  337,  337,  337,  337,  337,  103,  337,  337,
      337,  315,  317,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  156,  337,  337,  337,
       87,  141,  139,  138,  337,  318,  319,  137,  136,  329,
      133,  132,  131,  320,  130,  125,   89,  124,  121,  110,
      331,  109,  332,  108,   87,   96,  330,   56,   56,   56,

       56,   61,   61,   61,   61,   70,   70,   91,   70,  145,
       72,  145,  145,  321,  321,  321,  321,  333,  333,  333,
      333,   71,   60,  337,    5,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337
    } ;

static yyconst short int yy_chk[890] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,   11,   12,   13,   13,
       14,   19,   12,   40,    3,    4,   30,   30,   21,    3,
        4,   19,   40,  342,   23,   14,   21,   21,   22,   23,
       22,   22,   25,   25,   11,   23,   24,  335,   24,   24,

       34,   34,  333,   34,   34,   25,   24,   24,   24,   28,
       24,   24,   42,  105,  105,   42,   24,   24,   24,   24,
       24,   24,   28,   39,   28,   28,   24,   53,   61,   99,
       39,   25,   44,   41,   24,   41,   39,   24,   32,   44,
       47,   47,   32,   70,   41,  101,  328,   71,  327,  101,
       47,   32,   32,   47,   71,  119,   61,   99,  119,   32,
       32,   32,   32,   32,   32,   53,  326,   70,  325,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   33,   33,  102,  324,   79,   79,  102,

      111,   33,   33,   33,  111,   33,   79,   79,   83,   83,
      323,   33,   33,   33,   33,   33,   33,   83,   83,   79,
       79,   33,   84,   84,   85,   79,   85,   85,   87,   33,
       83,   83,  106,  106,  321,   85,   83,   86,   84,   86,
       89,  103,   86,   86,   87,  103,   84,  111,   85,   84,
       89,  104,   87,  314,  109,  104,   89,  107,  109,  107,
      107,  110,  313,  112,   89,  110,  103,  112,  113,  114,
      115,  117,  113,  114,  115,  117,  104,  152,  152,  109,
      120,  116,  103,  118,  120,  116,  104,  118,  312,  121,
      103,  150,  104,  121,  112,  109,  110,  122,  192,  192,

      104,  122,  109,  109,  123,  114,  116,  150,  123,  125,
      124,  113,  213,  125,  124,  150,  116,  126,  213,  115,
      117,  126,  116,  127,  311,  128,  120,  127,  116,  128,
      116,  118,  159,  159,  129,  130,  131,  121,  129,  130,
      131,  162,  154,  132,  310,  162,  125,  132,  159,  309,
      133,  308,  123,  124,  133,  158,  128,  125,  154,  158,
      127,  126,  142,  307,  142,  306,  154,  142,  142,  146,
      146,  128,  162,  129,  305,  131,  290,  127,  146,  146,
      130,  288,  132,  131,  132,  151,  198,  198,  147,  133,
      147,  146,  146,  147,  147,  151,  161,  146,  153,  153,

      161,  151,  287,  158,  245,  245,  160,  160,  153,  151,
      163,  256,  256,  164,  163,  160,  160,  164,  286,  165,
      166,  153,  160,  165,  166,  285,  153,  284,  160,  160,
      283,  167,  169,  168,  160,  167,  169,  168,  170,  171,
      161,  282,  170,  171,  172,  163,  173,  281,  172,  174,
      173,  166,  175,  174,  176,  280,  175,  177,  176,  164,
      179,  177,  279,  167,  179,  178,  165,  165,  168,  178,
      171,  181,  180,  170,  169,  181,  180,  182,  184,  183,
      185,  182,  184,  183,  185,  258,  205,  254,  187,  175,
      173,  186,  187,  176,  188,  186,  189,  253,  188,  195,

      189,  195,  205,  179,  195,  195,  177,  180,  193,  193,
      205,  178,  252,  184,  292,  292,  208,  214,  193,  181,
      208,  214,  187,  251,  185,  188,  182,  183,  199,  199,
      186,  193,  202,  202,  204,  215,  193,  189,  199,  215,
      249,  216,  202,  206,  204,  216,  248,  247,  217,  244,
      204,  199,  217,  206,  243,  202,  199,  218,  204,  206,
      202,  218,  219,  210,  208,  210,  219,  206,  210,  210,
      220,  242,  221,  222,  220,  215,  221,  222,  223,  224,
      225,  226,  223,  224,  225,  226,  227,  228,  230,  229,
      227,  228,  230,  229,  231,  232,  211,  262,  231,  232,

      234,  219,  233,  262,  234,  218,  233,  235,  236,  262,
      237,  235,  236,  221,  237,  207,  239,  238,  240,  220,
      239,  238,  240,  241,  201,  224,  255,  241,  225,  231,
      255,  200,  197,  234,  228,  229,  230,  246,  246,  232,
      235,  233,  236,  194,  259,  260,  261,  246,  259,  260,
      261,  263,  264,  237,  238,  263,  264,  191,  241,  190,
      246,  255,  257,  257,  265,  246,  240,  266,  265,  267,
      268,  266,  257,  267,  268,  269,  272,  270,  257,  269,
      272,  270,  155,  271,  273,  257,  263,  271,  273,  261,
      257,  149,  274,  275,  276,  264,  274,  275,  276,  277,

      278,  289,  291,  277,  278,  289,  291,  293,  144,  269,
      294,  293,  267,  270,  294,  266,  271,  295,  139,  296,
      138,  295,  273,  296,  272,  297,  298,  274,  299,  297,
      298,  300,  299,  100,   98,  300,  301,  276,  277,  302,
      301,  303,  304,  302,  315,  303,  304,  289,  315,  316,
      317,  291,  295,  316,  317,  318,  319,  320,  329,  318,
      319,  320,  329,  330,  331,  332,   94,  330,  331,  332,
      336,   78,   65,   64,   63,  302,  303,   59,   58,  315,
       51,   50,   49,  304,   48,   46,  336,   45,   43,   38,
      319,   37,  320,   36,  336,   29,  317,  338,  338,  338,

      338,  339,  339,  339,  339,  340,  340,   26,  340,  341,
       18,  341,  341,  343,  343,  343,  343,  344,  344,  344,
      344,   15,   10,    5,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexicalAnalyzer.l"
#define INITIAL 0
#line 2 "lexicalAnalyzer.l"
#include <stdio.h>
#include "y.tab.h"
int arrayIndexErr=0;
int lineCount=1;
int nestedCommentCount=0;
int scopeCount=0;
int commentFlag=0;
int functionCount;
char *tablePtr;
void addToken(char*);
#define DETECT_COMMENT 1

#line 684 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 26 "lexicalAnalyzer.l"



#line 839 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 338 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 825 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "lexicalAnalyzer.l"
{ lineCount++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 31 "lexicalAnalyzer.l"
{ BEGIN(DETECT_COMMENT);
					  nestedCommentCount++; 
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "lexicalAnalyzer.l"
{ nestedCommentCount++;
					  if(nestedCommentCount>1)
					  	commentFlag = 1;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "lexicalAnalyzer.l"
{ BEGIN(INITIAL); lineCount++;
						 if(nestedCommentCount>0)
                                			nestedCommentCount--;
                            			if(nestedCommentCount==0)
                            				BEGIN(INITIAL);
                    			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "lexicalAnalyzer.l"
{lineCount++;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "lexicalAnalyzer.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "lexicalAnalyzer.l"
{  return(AUTO); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "lexicalAnalyzer.l"
{  return(BREAK); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "lexicalAnalyzer.l"
{  return(CASE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "lexicalAnalyzer.l"
{  return(CHAR); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "lexicalAnalyzer.l"
{  return(CONST); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "lexicalAnalyzer.l"
{  return(CONTINUE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 59 "lexicalAnalyzer.l"
{  return(DEFAULT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 60 "lexicalAnalyzer.l"
{  return(DO); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 61 "lexicalAnalyzer.l"
{  return(DOUBLE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 62 "lexicalAnalyzer.l"
{  return(ELSE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 63 "lexicalAnalyzer.l"
{  return(ENUM); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 64 "lexicalAnalyzer.l"
{  return(EXTERN); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 65 "lexicalAnalyzer.l"
{  return(FLOAT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 66 "lexicalAnalyzer.l"
{  return(FOR); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 67 "lexicalAnalyzer.l"
{  return(GOTO); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 68 "lexicalAnalyzer.l"
{  return(IF); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 69 "lexicalAnalyzer.l"
{  return(INT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 70 "lexicalAnalyzer.l"
{  return(LONG); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 71 "lexicalAnalyzer.l"
{  return(REGISTER); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 72 "lexicalAnalyzer.l"
{  return(RETURN); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 73 "lexicalAnalyzer.l"
{  return(SHORT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 74 "lexicalAnalyzer.l"
{  return(SIGNED); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 75 "lexicalAnalyzer.l"
{  return(SIZEOF); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 76 "lexicalAnalyzer.l"
{  return(STATIC); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 77 "lexicalAnalyzer.l"
{  return(STRUCT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 78 "lexicalAnalyzer.l"
{  return(SWITCH); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 79 "lexicalAnalyzer.l"
{  return(TYPEDEF); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 80 "lexicalAnalyzer.l"
{  return(UNION); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 81 "lexicalAnalyzer.l"
{  return(UNSIGNED); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 82 "lexicalAnalyzer.l"
{  return(VOID); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 83 "lexicalAnalyzer.l"
{  return(VOLATILE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 84 "lexicalAnalyzer.l"
{  return(WHILE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 85 "lexicalAnalyzer.l"
{arrayIndexErr=1;printf("\n Invalid array Index %d",lineCount);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 86 "lexicalAnalyzer.l"
{arrayIndexErr=1;printf("\nInvalid array Index %d",lineCount);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 88 "lexicalAnalyzer.l"
{  addToken(yytext); return(IDENTIFIER); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 89 "lexicalAnalyzer.l"
{  addToken(yytext); return(STRING_LITERAL); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 91 "lexicalAnalyzer.l"
{  addToken(yytext); return(CONSTANT); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 92 "lexicalAnalyzer.l"
{  addToken(yytext); return(CONSTANT); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 93 "lexicalAnalyzer.l"
{  addToken(yytext); return(CONSTANT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 94 "lexicalAnalyzer.l"
{  addToken(yytext); return(CONSTANT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 97 "lexicalAnalyzer.l"
{  addToken(yytext); return(FLCONSTANT);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 98 "lexicalAnalyzer.l"
{  addToken(yytext); return(FLCONSTANT); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 99 "lexicalAnalyzer.l"
{  addToken(yytext); return(FLCONSTANT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 102 "lexicalAnalyzer.l"
{  return(ELLIPSIS); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 103 "lexicalAnalyzer.l"
{  return(RIGHT_ASSIGN); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 104 "lexicalAnalyzer.l"
{  return(LEFT_ASSIGN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 105 "lexicalAnalyzer.l"
{  return(ADD_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 106 "lexicalAnalyzer.l"
{  return(SUB_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 107 "lexicalAnalyzer.l"
{  return(MUL_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 108 "lexicalAnalyzer.l"
{  return(DIV_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 109 "lexicalAnalyzer.l"
{  return(MOD_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 110 "lexicalAnalyzer.l"
{  return(AND_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 111 "lexicalAnalyzer.l"
{  return(XOR_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 112 "lexicalAnalyzer.l"
{  return(OR_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 113 "lexicalAnalyzer.l"
{  return(RIGHT_OP); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 114 "lexicalAnalyzer.l"
{  return(LEFT_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 115 "lexicalAnalyzer.l"
{  return(INC_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 116 "lexicalAnalyzer.l"
{  return(DEC_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 117 "lexicalAnalyzer.l"
{  return(PTR_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 118 "lexicalAnalyzer.l"
{  return(AND_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 119 "lexicalAnalyzer.l"
{  return(OR_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 120 "lexicalAnalyzer.l"
{  return(LE_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 121 "lexicalAnalyzer.l"
{  return(GE_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 122 "lexicalAnalyzer.l"
{  return(EQ_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 123 "lexicalAnalyzer.l"
{  return(NE_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 124 "lexicalAnalyzer.l"
{  return(';'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 125 "lexicalAnalyzer.l"
{  scopeCount++;makeList("{",'p',lineCount); return('{'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 126 "lexicalAnalyzer.l"
{  scopeCount--;functionCount++;makeList("}",'p',lineCount); return('}'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 127 "lexicalAnalyzer.l"
{  return(','); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 128 "lexicalAnalyzer.l"
{  return(':'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 129 "lexicalAnalyzer.l"
{  return('='); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 130 "lexicalAnalyzer.l"
{  return('('); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 131 "lexicalAnalyzer.l"
{  return(')'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 132 "lexicalAnalyzer.l"
{  return('['); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 133 "lexicalAnalyzer.l"
{  return(']'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 134 "lexicalAnalyzer.l"
{  return('.'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 135 "lexicalAnalyzer.l"
{  return('&'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 136 "lexicalAnalyzer.l"
{  return('!'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 137 "lexicalAnalyzer.l"
{  return('~'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 138 "lexicalAnalyzer.l"
{  return('-'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 139 "lexicalAnalyzer.l"
{  return('+'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 140 "lexicalAnalyzer.l"
{  return('*'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 141 "lexicalAnalyzer.l"
{  return('/'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 142 "lexicalAnalyzer.l"
{  return('%'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 143 "lexicalAnalyzer.l"
{  return('<'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 144 "lexicalAnalyzer.l"
{  return('>'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 145 "lexicalAnalyzer.l"
{  return('^'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 146 "lexicalAnalyzer.l"
{  return('|'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 147 "lexicalAnalyzer.l"
{  return('?'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 150 "lexicalAnalyzer.l"
{ lineCount++; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 151 "lexicalAnalyzer.l"
{ lineCount++; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 153 "lexicalAnalyzer.l"
{}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 154 "lexicalAnalyzer.l"
{}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 155 "lexicalAnalyzer.l"
{lineCount++;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 156 "lexicalAnalyzer.l"
{ }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 158 "lexicalAnalyzer.l"
ECHO;
	YY_BREAK
#line 1442 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DETECT_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 338 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 338 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 337);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 158 "lexicalAnalyzer.l"

yywrap()
{
	return(1);
}

void addToken(char *yytext)
{
  int len = strlen(yytext);
  tablePtr = (char*)malloc((len+1)*sizeof(char));
  strcpy(tablePtr, yytext);
}

