/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
static yyconst short int yy_accept[239] =
    {   0,
        0,    0,    0,    0,   32,   31,   21,   22,   31,   16,
       12,   11,   20,   14,   12,   12,   14,   12,    8,   10,
       13,   10,    7,    7,   20,    9,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,   23,   24,    1,    7,    7,    7,    7,   30,   29,
       30,   30,   21,    0,    0,   10,   16,   16,   15,    0,
        0,    6,    0,    0,   17,   17,   26,   25,    8,    9,
        9,    7,    0,   16,    7,    7,    7,    7,    7,    7,
        7,    2,    7,    7,    7,    7,    7,    7,    2,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        1,    0,    1,    1,    0,    1,    7,    7,    7,    7,
       28,   27,    0,    0,    0,    0,    0,    0,    0,    0,
       15,   18,    0,    6,    6,    0,   25,    0,    9,    0,
        5,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    1,    7,
        7,    2,    7,    0,    0,    0,    0,    0,    0,   19,
       17,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    0,    7,    0,    0,    0,    3,    0,    0,

        0,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    0,    0,    7,    0,    0,
        0,    7,    7,    7,    2,    7,    7,    7,    0,    0,
        4,    7,    7,    0,    7,    7,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   26,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   24,   41,   42,   43,   44,
       45,   46,   24,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,    1,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    2,    3,    4,    5,    1,    1,    1,    6,    7,
        1,    1,    1,    1,    4,    8,    1,    9,    1,    1,
        4,    4,    4,   10,   10,   10,   11,    1,    1,    1,
       12,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,    1,    1,    1
    } ;

static yyconst short int yy_base[259] =
    {   0,
        0,   53,   57,   58,  586,  618,   60,  618,  563,   60,
      618,  618,    0,  618,  548,   48,  560,   55,   55,  555,
      554,  553,  547,   71,  618,    0,   50,   52,   62,   69,
       68,   41,   58,   79,   70,   82,   86,   57,   90,   92,
       93,  618,  618,  120,  101,  102,  112,  100,  618,  618,
      546,  542,  128,  508,  503,  618,  145,  504,  519,  148,
      514,    0,    0,  504,  136,  139,  618,    0,  142,  504,
      167,  482,   63,  452,  452,  128,  154,  136,  104,  142,
      160,  139,  144,  161,  147,  164,  166,  167,  449,  168,
      171,  172,  173,  174,  175,  179,  177,  187,  197,  193,

      224,  453,  228,  232,  452,  236,  176,  198,  214,  225,
      618,  618,  434,  427,  424,  421,  421,  418,  239,  457,
      257,  618,  452,    0,    0,  251,    0,  442,  252,  243,
      618,  229,  244,  246,  248,  250,  251,  253,  252,  254,
      257,  260,  262,  263,  264,  267,  269,  204,  273,  275,
      276,  278,  279,  283,  281,  284,  286,  287,  318,  285,
      298,  329,  307,  427,  413,  408,  416,  417,  407,  618,
      435,  296,  306,  308,  309,  311,  316,  317,  319,  318,
      322,  325,  323,  324,  335,  343,  345,  330,  346,  327,
      351,  348,  377,  371,    0,  405,  419,  618,  415,  447,

      399,  355,  358,  356,  359,  361,  362,  366,  367,  368,
      363,  378,  380,  369,  382,  435,  428,  401,  348,  156,
      389,  387,  392,  388,  416,  393,  398,  394,  149,   71,
       67,  406,  400,  429,  411,  408,  430,  618,  481,  493,
      497,  498,  503,  505,  508,  517,  527,  539,  546,  548,
      550,  560,  571,  582,  588,  591,  595,  605
    } ;

static yyconst short int yy_def[259] =
    {   0,
      238,    1,  239,  239,  238,  238,  238,  238,  238,  240,
      238,  238,  241,  238,  242,  238,  238,  238,  243,  238,
      238,  238,  244,  244,  238,  245,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  238,  238,  246,  244,  244,  244,  244,  238,  238,
      238,  238,  238,  238,  238,  238,  240,  247,  248,  240,
      249,  250,  251,  238,  238,  238,  238,  252,  243,  243,
      243,  244,  238,  247,  245,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,

      246,  238,  246,  246,  238,  246,  244,  244,  244,  244,
      238,  238,  238,  238,  238,  238,  238,  238,  247,  248,
      240,  238,  249,  250,  251,  238,  252,  238,  243,  238,
      238,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  246,  244,
      244,  253,  244,  238,  238,  238,  238,  238,  238,  238,
      238,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  254,  255,  256,  238,  238,  238,  238,  238,

      238,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  257,  258,  255,  256,  238,
      238,  244,  244,  244,  244,  244,  244,  244,  257,  258,
      258,  244,  244,  238,  244,  244,  238,    0,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238
    } ;

static yyconst short int yy_nxt[677] =
    {   0,
        6,    7,    8,    9,   10,    6,   11,   12,   13,   14,
       14,   15,   16,   14,   16,   17,   18,   19,   14,   14,
       20,   21,   22,   23,   23,   24,   14,   25,   14,   12,
       26,   27,   28,   29,   30,   31,   32,   33,   23,   34,
       23,   35,   23,   23,   23,   23,   36,   37,   38,   39,
       40,   41,   23,   23,   23,   42,   43,   12,   44,   50,
       50,   53,   58,   64,   59,   65,   67,   73,   51,   51,
       64,   68,   69,   52,   52,   74,   73,  231,   73,   71,
      130,  231,   86,   73,   73,   87,   45,   60,   73,   46,
       71,  131,   47,   78,   73,   73,   73,   73,   77,   76,

       79,   54,   88,   48,   81,   73,   80,   55,   73,   83,
       97,   84,   73,   82,   91,   89,   73,   92,   73,   73,
       85,  101,   90,  102,   93,   94,   73,   73,   73,   53,
       73,  100,   78,   98,   95,  135,   99,   96,   73,  107,
      104,  105,  106,  108,  110,   80,   87,   58,   89,   59,
      238,   64,  121,   65,   73,  109,   66,   64,  217,   69,
      126,  113,   73,  126,  114,   73,   71,  115,   73,   54,
       73,  126,   60,   73,  126,   55,  132,   71,  116,  128,
       73,  128,  238,  134,  129,  136,   73,   73,  138,  133,
       73,  139,   73,   73,   73,  141,  137,   73,   73,   73,

       73,   73,   73,   73,  198,   73,  150,  160,  142,  145,
      140,  148,   89,   73,  144,  143,   89,  147,  152,   73,
      146,  151,  153,   73,   73,  101,  154,  102,  149,  101,
       73,  102,  158,  101,  155,  102,  156,  101,  157,  102,
       73,  238,  161,   58,  104,  105,  106,  182,  104,  105,
      106,   73,  104,  159,  106,   73,  104,  159,  106,   58,
      130,   59,  162,  128,  163,  128,  157,  238,  171,  129,
       73,  131,   73,   89,   73,  172,   73,   73,   73,   73,
       73,   89,  175,   73,   60,  176,   73,   89,   73,   73,
       73,  178,  177,   73,   89,   73,   89,  173,  174,   73,

       89,   73,   73,  179,   73,   73,   89,   73,  183,   73,
       73,   73,   73,   73,  187,  181,  180,  190,   89,  101,
      189,  102,   73,  184,   73,  185,  186,  188,  191,  192,
      193,  162,   73,   73,   73,   73,   89,   73,  104,  159,
      106,  162,   73,   73,   73,   73,   72,  202,   73,   73,
       73,   73,  204,   73,   89,   73,   73,  217,  203,  195,
      208,   73,  205,  210,  207,   89,  206,  209,  211,   73,
       89,   73,   73,   89,   73,  215,  212,   73,  193,  213,
      217,   73,   73,  214,   73,   73,   89,   73,   73,   73,
      221,   89,   73,   73,   73,   73,  162,   73,  222,  223,

      225,   89,   89,   89,   73,   89,   73,  195,   73,  224,
      217,   89,  227,   73,   73,  226,   89,  234,   73,   73,
       73,  228,  113,  233,   73,  114,   73,   73,  115,   89,
      237,  237,   73,  235,   73,  236,  232,   73,  231,  116,
       89,   89,   73,   89,  217,  225,   89,  200,  221,  198,
      220,  198,  171,  201,  200,  199,  198,  197,  196,  171,
      170,   59,  169,  113,  168,  167,  114,  166,  165,  115,
       54,   54,  164,  103,  103,   73,   55,   55,   73,  119,
      116,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   57,   57,   61,   61,   62,   73,   62,
       70,   70,   70,   72,   72,   72,   75,   75,  103,  238,
      103,   66,  122,   59,  103,  103,  103,   58,   58,   58,
       58,  119,   58,   58,   58,   58,   58,   58,   58,  120,
      120,  118,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  123,  117,  112,  123,  123,  124,  124,  125,  125,
      127,  127,  111,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  194,   73,   56,   56,   56,   66,   63,  194,
      194,  194,  194,  216,   56,  238,  238,  238,  238,  238,
      238,  216,  238,  216,  218,  238,  218,  218,  218,  219,

      219,  229,  238,  229,  229,  230,  230,  238,  230,  230,
      230,  230,  230,  230,  230,  230,  230,    5,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238
    } ;

static yyconst short int yy_chk[677] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    7,   10,   16,   10,   16,   18,   32,    3,    4,
       19,   18,   19,    3,    4,   24,   27,  231,   28,   19,
       73,  230,   32,   38,   33,   32,    2,   10,   29,    2,
       19,   73,    2,   29,   31,   30,   35,   24,   28,   27,

       29,    7,   33,    2,   30,   34,   29,    7,   36,   31,
       38,   31,   37,   30,   35,   34,   39,   36,   40,   41,
       31,   44,   34,   44,   37,   37,   48,   45,   46,   53,
       79,   41,   45,   39,   37,   79,   40,   37,   47,   45,
       44,   44,   44,   46,   48,   45,   46,   57,   47,   57,
       60,   65,   60,   65,   76,   47,   66,   69,  229,   69,
       65,   53,   78,   66,   53,   82,   69,   53,   80,   53,
       83,   65,   57,   85,   66,   53,   76,   69,   53,   71,
       77,   71,   71,   78,   71,   80,   81,   84,   82,   77,
       86,   83,   87,   88,   90,   85,   81,   91,   92,   93,

       94,   95,  107,   97,  220,   96,   95,  107,   86,   92,
       84,   94,   87,   98,   91,   88,   90,   93,   96,  100,
       92,   95,   97,   99,  108,  101,   98,  101,   94,  103,
      148,  103,  100,  104,   98,  104,   99,  106,   99,  106,
      109,  119,  108,  119,  101,  101,  101,  148,  103,  103,
      103,  110,  104,  104,  104,  132,  106,  106,  106,  121,
      130,  121,  109,  126,  110,  126,  110,  129,  126,  129,
      133,  130,  134,  132,  135,  133,  136,  137,  139,  138,
      140,  134,  137,  141,  121,  138,  142,  139,  143,  144,
      145,  142,  141,  146,  135,  147,  140,  136,  136,  149,

      144,  150,  151,  145,  152,  153,  143,  155,  149,  154,
      156,  160,  157,  158,  153,  147,  146,  157,  156,  159,
      155,  159,  172,  150,  161,  151,  152,  154,  158,  161,
      162,  160,  173,  163,  174,  175,  172,  176,  159,  159,
      159,  163,  177,  178,  180,  179,  162,  174,  181,  183,
      184,  182,  176,  190,  173,  162,  188,  219,  175,  162,
      182,  185,  177,  184,  180,  178,  179,  183,  185,  186,
      181,  187,  189,  188,  192,  190,  186,  191,  193,  187,
      194,  202,  204,  189,  203,  205,  191,  206,  207,  211,
      221,  204,  208,  209,  210,  214,  192,  194,  202,  203,

      208,  210,  205,  209,  212,  207,  213,  193,  215,  206,
      218,  211,  214,  222,  224,  213,  212,  225,  223,  226,
      228,  215,  221,  224,  227,  221,  233,  218,  221,  226,
      234,  237,  232,  227,  236,  228,  222,  235,  217,  221,
      223,  232,  225,  236,  216,  235,  233,  201,  200,  199,
      197,  196,  171,  169,  168,  167,  166,  165,  164,  128,
      123,  120,  118,  237,  117,  116,  237,  115,  114,  237,
      234,  237,  113,  105,  102,   89,  234,  237,   75,   74,
      237,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  240,  240,  240,  240,  240,  240,  240,

      240,  240,  240,  240,  240,  241,  241,  242,   72,  242,
      243,  243,  243,  244,  244,  244,  245,  245,  246,   70,
      246,   64,   61,   59,  246,  246,  246,  247,  247,  247,
      247,   58,  247,  247,  247,  247,  247,  247,  247,  248,
      248,   55,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  249,   54,   52,  249,  249,  250,  250,  251,  251,
      252,  252,   51,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  253,   23,   22,   21,   20,   17,   15,  253,
      253,  253,  253,  254,    9,    5,    0,    0,    0,    0,
        0,  254,    0,  254,  255,    0,  255,  255,  255,  256,

      256,  257,    0,  257,  257,  258,  258,    0,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "LexicalScanner.l"
#define INITIAL 0
#line 2 "LexicalScanner.l"
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <string.h>
int var=0,i,nc=0,commLine=0,flag=0;
int lineNumber=1;
int cBrac=0;

FILE *Smbl,*Cnst;						// Smbl for symbol, Cnst for constants
char *Mul_comment,*inputFile, Sng_comment[1000];

void insertToTable(char *yytext,char type);
void storeMultiLineComment(char *yytext);
void storeSingleLineComment(char *yytext);

struct Node {
	char *tname;
	int av;
	struct Node *next;
}*head=NULL;

#define COMMENT_DETECTION 1

#line 617 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 46 "LexicalScanner.l"


#line 774 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 239 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 618 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 48 "LexicalScanner.l"
{
	insertToTable(yytext,'d'); //preprocessor directive rule
	printf("%s : %d : Preprocessor rule found - %s\n",inputFile,lineNumber,yytext);
	}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 53 "LexicalScanner.l"
insertToTable(yytext,'k');
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 "LexicalScanner.l"
insertToTable(yytext,'k'); //keyword rule
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 56 "LexicalScanner.l"
{	int i,j=0;char temp1[50]={'\0'}, temp2[50]={'\0'};
												for(i=0;yytext[i]!=' ';i++)
												{
													temp1[i] = yytext[i];
												}
												
												insertToTable(temp1,'k');
												for(;yytext[i]!='(';i++){
													temp2[j]=yytext[i];
													j++;
												}

												insertToTable(temp2,'j');  //procedure rule
											}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 71 "LexicalScanner.l"
{	int i,j=0;char temp[50]={'\0'};
							
							for(i=0;yytext[i]!='[';i++)
							{
								temp[j] = yytext[i];
								j++;
							}

								insertToTable(temp,'a'); // array rule
						}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 82 "LexicalScanner.l"
{	int i,j=0;char temp[50]={'\0'};
					for(i=1;yytext[i]!='\0';i++)
					{
						temp[j++] = yytext[i];
					}
						insertToTable(temp,'q'); // pointer rule
				}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 90 "LexicalScanner.l"
{
	insertToTable(yytext,'i'); // variable rule
	printf("%s : %d : Identifier found - %s\n",inputFile,lineNumber,yytext);
	}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 94 "LexicalScanner.l"
{
	insertToTable(yytext,'c'); //integer constants rule
	printf("%s : %d : Integer found - %s\n",inputFile,lineNumber,yytext);
	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 98 "LexicalScanner.l"
{ printf("%s : %d : Invalid Identifier - %s\n",inputFile,lineNumber,yytext); } // invalid identifier
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 101 "LexicalScanner.l"
insertToTable(yytext,'r'); //operator rules
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 102 "LexicalScanner.l"
insertToTable(yytext,'l');
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 103 "LexicalScanner.l"
insertToTable(yytext,'o');
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "LexicalScanner.l"
insertToTable(yytext,'e');
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 105 "LexicalScanner.l"
insertToTable(yytext,'p');
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 108 "LexicalScanner.l"
{
	insertToTable(yytext,'s'); //string constants rule
	printf("%s : %d : String constant found - %s\n",inputFile,lineNumber,yytext);
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 112 "LexicalScanner.l"
{
				if(nc<=0) //invalid String
				printf("%s : %d : String does not end\n",inputFile,lineNumber);	
			}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 116 "LexicalScanner.l"
insertToTable(yytext,'f');  // float constant rule
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 117 "LexicalScanner.l"
{	char temp[50]={'\0'};
							temp[0] = yytext[1];
							printf("%s : %d : Character constant found - '%c'\n",inputFile,lineNumber,temp[0]);
							insertToTable(temp,'z');  // character constant rule
						}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 122 "LexicalScanner.l"
{printf("%s : %d : Invalid Character constant - %s\n",inputFile,lineNumber,yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 124 "LexicalScanner.l"
;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 125 "LexicalScanner.l"
;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 126 "LexicalScanner.l"
lineNumber++;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 128 "LexicalScanner.l"
{ 	cBrac++;
	insertToTable(yytext,'p');
	 }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 132 "LexicalScanner.l"
{	cBrac--;
	insertToTable(yytext,'p');
	 }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 136 "LexicalScanner.l"
{
	printf("%s : %d : Single comment found\n",inputFile,lineNumber);
	storeSingleLineComment(yytext);	
	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 141 "LexicalScanner.l"
{  
                BEGIN(COMMENT_DETECTION);
                nc++;
                commLine++;
                storeMultiLineComment("\n\n");
            }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 148 "LexicalScanner.l"
{ 
                            nc++;
                            if(nc>1)
                            {
								printf("%s : %d : Nested Comment found\n",inputFile,lineNumber);
                                flag++;
                            }
                         }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 157 "LexicalScanner.l"
{
                            if(nc>0)
                                nc--;
                            else
			    	printf("%s : %d : Error:Closing comment found before opening\n",inputFile,lineNumber);
                            
                            if(nc==0){
				printf("%s : %d : Multi-line comment found\n",inputFile,lineNumber);
                            	BEGIN(INITIAL);
			    }
                    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 169 "LexicalScanner.l"
{  
                 commLine++;
                 lineNumber++;
                 storeMultiLineComment("\n");
                }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 175 "LexicalScanner.l"
{storeMultiLineComment(yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 178 "LexicalScanner.l"
ECHO;
	YY_BREAK
#line 1093 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_DETECTION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 239 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 239 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 238);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 178 "LexicalScanner.l"


int main(int argc,char **argv)
{
	Mul_comment = (char*)malloc(100*sizeof(char));
	yyin=fopen(argv[1],"r");
	inputFile=argv[1];

	Smbl=fopen("Symbol Table.txt","w");				 //File to write and save Symbol Table for given input
	fprintf(Smbl,"\t\t\t\t\t\t\t\t\t\t Symbol Table:\n\n\n\n \t\tLine Number\t\t\tLexeme\t\t\t\tType\t\t\tAttribute Value\n");

	Cnst=fopen("Constant Table.txt","w");				// File to write and Constant Table for given input
	fprintf(Cnst,"\t\t\t\t\t\t\t\t\t\t Constants Table:\n\n\n\n \t\tLine Number\t\t\tLexeme\t\t\tType\t\t\tAttribute Value\n");

	yyout=fopen("Tokens List.txt","w");				// File to write all token in source program
	fprintf(yyout,"\t\t\t\t\t\t\t\t\t\t Token List:\n\n\n\n \t\tLine Number\t\t\tLexeme\t\t\tToken\t\t\t\tAttribute Value\n");

	yylex();
	
    	if(nc!=0)
    		printf("%s : %d : Comment does not end\n",inputFile,lineNumber);
    		
    	if(cBrac!=0)
    		printf("%s : %d : Unbalanced Braces {}\n",inputFile,lineNumber);
    
    	fprintf(yyout,"\n");
    	if(flag > 0)
    	{
			commLine = 0;
			fprintf(yyout,"\n\nComment (%d lines):\n",commLine);
			printf("\n%s : %d Nested comment(s) found\n",inputFile,flag);
    	}
    	else
    	{
	    	int i;
		fprintf(yyout,"\n\nMultiLineComment (%d lines):\n\n",commLine);
		fputs(Mul_comment,yyout);
		fprintf(yyout,"\n\nSingleLineComment :\n\n");
		fputs(Sng_comment,yyout);
	}
    
	fclose(yyout);
	fclose(Smbl);
	fclose(Cnst);	
}

void storeSingleLineComment(char *yytext)
{
	int length = strlen(yytext);
	int i, j;
	char *extra;
	extra = (char*)malloc((length+1)*sizeof(char));
	for(j=2,i=0;yytext[j]!='\0';j++,i++)
	{
		extra[i] = yytext[j];
	}	
	strcat(extra,"\n");	//To print on new line
	strcat(Sng_comment,extra);	//Copy to list of single comments
}
void storeMultiLineComment(char *yytext)
{
    int len1, len2;
    char *extra;

    len1 = strlen(Mul_comment);
    len2 = strlen(yytext);
    extra = (char*)malloc((len1+1)*sizeof(char));
    strcpy(extra,Mul_comment);
    Mul_comment = (char*)malloc((len1+len2+1)*sizeof(char));
    strcat(extra,yytext);
    strcpy(Mul_comment,extra);
}
void insertToTable(char *yytext,char type)
{
    int l1 = strlen(yytext), i;
	
    
    char token[30];
    struct Node *current = NULL, *temp = NULL;

    switch(type)
    {
	case 'd': strcpy(token,"Preprocessor Statement");break;

        case 'k': strcpy(token,"Keyword");break;
         
        case 'j': strcpy(token,"Procedure");break;              
       
        case 'a': strcpy(token,"Array");break;

	case 'q': strcpy(token,"Pointer");break;
        
        case 'i': strcpy(token,"Identifier");break;
	 	
	case 'r': strcpy(token,"Relational Op");break;

        case 'p': strcpy(token,"Punctuator");break;
       	
       	case 'o': strcpy(token,"Arithmetic Op");break;   
        
        case 'c': strcpy(token,"Integer Constant");break;

        case 'f': strcpy(token,"Float Constant");break;

        case 'z': strcpy(token,"Character Constant");break;                                
      	
      	case 'e': strcpy(token,"Assignment Op");break;
      	
      	case 'l': strcpy(token,"Logical Op");break;	
    	
    	case 's': strcpy(token,"String Literal");break;
    }

    if(nc<=0)
    {
	    current = head;
	    for(i=0;i<var;i++)
	    {    	
	    	if(strcmp(current->tname,yytext)==0)
	    		{
	    			break;
	    		}
	    		current = current->next;
	    }

	    if(i==var)
	    {    	
	    	temp = (struct Node *)malloc(sizeof(struct Node));
	    	temp->av = i;
	    	temp->tname = (char *)malloc(sizeof(char)*(l1+1));
	    	strcpy(temp->tname,yytext);
	    	temp->next = NULL;

	    	if(head==NULL)
	    	{    		
	    		head = temp;
	    	}
	    	else
	    	{
	    		current = head;
	    		while(current->next!=NULL)
	    		{
	    			current = current->next;
	    		}    
		    	current->next = temp;
		}
		   	
    		var++;	
	    }
    }

	if(type =='i' || type == 'a' || type == 'q' || type=='j')
	{	
		fprintf(Smbl,"\n%25d%30s%30s%30d",lineNumber,yytext,token,i);
	}
	switch(type)
	{		
		case 'c' : fprintf(Cnst,"\n%25d%30s%20s%30d",lineNumber,yytext,"int",i);
				    break;

		case 'f' : fprintf(Cnst,"\n%25d%30s%20s%30d",lineNumber,yytext,"float",i);
				    break;

		case 'z' : fprintf(Cnst,"\n%25d%30s%20s%30d",lineNumber,yytext,"char",i);
				    break;
	}

   	fprintf(yyout,"\n%25d%30s%30s%30d",lineNumber,yytext,token,i);
}
                                                                                                    
int yywrap()
{
 return(1);
}